import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tesla Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="bg-black text-white hover:bg-white">Home</h1>
      </main>
    </>
  );
}
